// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qjfnyysuajsritwbindx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFqZm55eXN1YWpzcml0d2JpbmR4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2NDgzODEsImV4cCI6MjA1NzIyNDM4MX0.SWCc3GkX_e8mVpZPcB3-eBvDN0v-m1iTh7vNzESLBLs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);